### ISSUE TITLE
No update since 2023_07_05

### ISSUE THREAD

**Issue by MartinoMensio** [MartinoMensio/claimreview-data#1]
TODO: check logs and see what's wrong

**Comment by MartinoMensio** [comment]
Firewall issue. Solved 2023_07_28

**Comment by rtroncy** [comment]
Well done @MartinoMensio 
Will we have a gap from 05/07 until 28/07 or did the last update collect all factchecks from this period?

**Comment by MartinoMensio** [comment]
@rtroncy the data releases should be cumulative (unless data is deleted from fact checkers or aggregators). So you should find the fact-checks for the missing period in the latest release. I haven't looked at the new data yet so let me know if something is missing!
Cheers! :)
